ORG 1000h
vocales DB "aeiou"
cadena DB "amarilloe$"
result DB 0,0,0,0,0



ORG 3000h ; SUBRUTINA
;AH CHAR ENVIADO POR VALOR-REGISTRO
;DX GUARDA EL RESULTADO 
;CX CADENA ENVADA POR REF- PILA

CONCAR:
PUSH BX ; POR REUSO
MOV BX, SP ; PARA ACCEDER A LA PILA
ADD BX, 4 ;  POR QUE ESTA EN EL RETORNO EN LA PILA 
PUSH AX ; POR REUSO
PUSH DX ; POR REUSO
MOV BX, [BX] ; RECUPERO LA REFERENCIA

MOV DX,0; INICIALIZO EL CONTADOR
WHILE: MOV AL,[BX] ; TRAIGO EL CARACTER DE LA CADENA
CMP AL, 24h ; VEO SI LA CADENA TERMINA CON $
JZ FIN_WHILE
CMP AL, AH ; COMPARO CON LA VOCAL 
JNZ NO_CONTAR 
ADD DX,1 ; SI ES IGUAL CUENTO
NO_CONTAR:
INC BX ; AVANZO EN LA CADENA
JMP WHILE ; ITERO 

FIN_WHILE: 
MOV AX, DX ;GUARDO EL CONTADOR EN AX
POP DX ; TRAIGO LA DIRECCION DE GUARDADO
MOV BX,DX 
MOV [BX], AX ; GUARDO EL RESULTADO
POP AX
POP BX ; REUSO
RET

ORG 2000h ; PROGRAMA PRINCIPAL
MOV CX, OFFSET cadena
MOV DX, OFFSET result
MOV BX, OFFSET vocales

BUCLE: CMP BX,CX ; OFFSET VOC - OFFSET CADENA (TERMINO VOCALES)
JZ FIN_BUCLE
MOV AH,[BX] ;TRAIGO LA VOCAL

PUSH CX
CALL CONCAR
POP CX

INC BX ; AVANZO EN VOCALES
INC DX; AVANZO EN RESULT
JMP BUCLE

FIN_BUCLE: HLT

END



