ORG 1000h 
TABLAN1 DW 1,25,35,40,2
FINTABLA DB ?
n2 EQU 25
CONT DB ?


ORG 3000h 
;AX TIENE DATO DE N1
;CX TIENE DATO DE N2
MAYOR_IGUAL:
PUSH BX 
PUSH AX
PUSH CX
MOV BX, SP 
ADD BX, 8  ; SP + 8 --> POSICION DE LA DIRECION DE N1
MOV BX, [BX] ; TRAIGO OFFSET DE N1
MOV AX, [BX] ; COPIO EL VALOR DE N1 

IF: CMP CX,AX ; N2-N1
JNS FIN 
MOV [BX], CX ; COPIO EL VALOR DE N2 EN [BX] QUE TIENE EL OFFSET DE N1 
FIN: 
POP CX
POP AX
POP BX
RET


ORG 2000h ; PROGRAMA
MOV AX, OFFSET TABLAN1 
MOV CX, n2 ; VALOR DE N2

MOV DL, OFFSET FINTABLA - OFFSET TABLAN1
LOOP: CMP DL,0
      JZ FIN_LOOP
PUSH AX ; APILA DIR N1
CALL MAYOR_IGUAL
POP AX
ADD AX,2
SUB DL,2
JMP LOOP

FIN_LOOP:
HLT

END
